'use client';

import React, { useState } from 'react';
import {
  AskConversation,
  AskMessage,
  SourceItem,
  AskResponseData,
} from './types';
import {
  INITIAL_CONVERSATIONS,
  MOCK_PROJECT_ALPHA_RESPONSE,
  MOCK_SOURCES,
} from './mockData';
import { AskMyWorldHeader } from './AskMyWorldHeader';
import { EmptyAskState } from './EmptyAskState';
import { UserMessage } from './UserMessage';
import { AIResponse } from './AIResponse';
import { AIThinkingState } from './AIThinkingState';
import { AskComposer } from './AskComposer';
import { ContextPanel } from './ContextPanel';
import { ConversationHistory } from './ConversationHistory';
import { Modal } from '../ui/Modal';
import { Button } from '../ui/Button';
import { Badge } from '../ui/Badge';
import { Mail, Calendar, HardDrive, FileText, ExternalLink, Sparkles } from 'lucide-react';
import { ConnectorId } from '../shell/ConnectorModal';
import { useToast } from '../ui/Toast';

export interface AskMyWorldViewProps {
  onNavigate?: (pageId: string) => void;
  onOpenConnector?: (connectorId: ConnectorId) => void;
}

export const AskMyWorldView: React.FC<AskMyWorldViewProps> = ({
  onNavigate,
  onOpenConnector,
}) => {
  const { addToast } = useToast();
  const [conversations, setConversations] = useState<AskConversation[]>(INITIAL_CONVERSATIONS);
  const [activeConversationId, setActiveConversationId] = useState<string | null>(
    'conv-project-alpha'
  );
  const [isThinking, setIsThinking] = useState(false);
  const [isHistoryOpen, setIsHistoryOpen] = useState(false);
  const [isContextPanelOpen, setIsContextPanelOpen] = useState(true);
  const [isMobile, setIsMobile] = useState(false);
  const [selectedSourceForModal, setSelectedSourceForModal] = useState<SourceItem | null>(null);

  React.useEffect(() => {
    const checkMobile = () => {
      setIsMobile(window.innerWidth < 1024);
    };
    checkMobile();
    window.addEventListener('resize', checkMobile);
    return () => window.removeEventListener('resize', checkMobile);
  }, []);

  const activeConv = conversations.find((c) => c.id === activeConversationId);

  const handleNewConversation = () => {
    setActiveConversationId(null);
    addToast({
      type: 'info',
      title: 'New Conversation',
      description: 'Ready for your new workspace query.',
    });
  };

  const handleSendPrompt = (text: string) => {
    const timestamp = 'Just now';
    const userMsg: AskMessage = {
      id: `msg-${Date.now()}`,
      sender: 'user',
      text,
      timestamp,
    };

    let convId = activeConversationId;
    let updatedConvs = [...conversations];

    if (!convId) {
      // Create new conversation
      const newConv: AskConversation = {
        id: `conv-${Date.now()}`,
        title: text.length > 30 ? `${text.substring(0, 30)}...` : text,
        updatedAt: 'Just now',
        messages: [userMsg],
      };
      updatedConvs.unshift(newConv);
      convId = newConv.id;
      setActiveConversationId(convId);
      setConversations(updatedConvs);
    } else {
      // Append user message to active conversation
      updatedConvs = updatedConvs.map((c) => {
        if (c.id === convId) {
          return {
            ...c,
            updatedAt: 'Just now',
            messages: [...c.messages, userMsg],
          };
        }
        return c;
      });
      setConversations(updatedConvs);
    }

    // Trigger AI thinking state & mock response
    setIsThinking(true);

    setTimeout(() => {
      setIsThinking(false);

      // Construct a mock AI response tailored to user's query
      let responseData: AskResponseData;
      if (text.toLowerCase().includes('alpha')) {
        responseData = MOCK_PROJECT_ALPHA_RESPONSE;
      } else {
        responseData = {
          id: `resp-${Date.now()}`,
          summaryText: `Synthesized workspace context for "${text}".`,
          insights: [
            {
              id: `ins-gen-${Date.now()}`,
              title: 'Context Alignment',
              content: `Reviewed connected Gmail, Calendar, and Drive documents. Found 2 relevant updates regarding "${text}".`,
              priority: 'medium',
              sources: MOCK_SOURCES,
            },
          ],
          recommendedNextStep: {
            text: 'Schedule a brief sync with Rahul to confirm alignment.',
            actionLabel: 'Prepare brief',
          },
          sources: MOCK_SOURCES,
          whyExplanation: `This response was generated by cross-referencing recent Gmail threads and Drive files matching "${text}".`,
        };
      }

      const aiMsg: AskMessage = {
        id: `msg-ai-${Date.now()}`,
        sender: 'ai',
        text: responseData.summaryText,
        timestamp: 'Just now',
        aiData: responseData,
      };

      setConversations((prev) =>
        prev.map((c) => {
          if (c.id === convId) {
            return {
              ...c,
              updatedAt: 'Just now',
              messages: [...c.messages, aiMsg],
            };
          }
          return c;
        })
      );
    }, 1200);
  };

  const handleRenameConversation = (convId: string, newTitle: string) => {
    setConversations((prev) =>
      prev.map((c) => (c.id === convId ? { ...c, title: newTitle } : c))
    );
  };

  const handleDeleteConversation = (convId: string) => {
    setConversations((prev) => prev.filter((c) => c.id !== convId));
    if (activeConversationId === convId) {
      setActiveConversationId(null);
    }
  };

  return (
    <div className="space-y-6 animate-fadeIn pb-12 min-h-[calc(100vh-8rem)] flex flex-col justify-between">
      {/* 1. Header */}
      <AskMyWorldHeader
        onNewConversation={handleNewConversation}
        onToggleHistory={() => setIsHistoryOpen(true)}
        onToggleContextPanel={() => setIsContextPanelOpen(!isContextPanelOpen)}
        isContextPanelOpen={isContextPanelOpen}
        activeConversationTitle={activeConv?.title}
      />

      {/* 2. Main Body Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 flex-1 items-start max-w-7xl mx-auto w-full">
        {/* Main Conversation Workspace Column */}
        <div
          className={cn(
            'flex flex-col min-h-[500px] justify-between space-y-4 w-full transition-all duration-200',
            isContextPanelOpen ? 'lg:col-span-8 xl:col-span-8' : 'lg:col-span-12'
          )}
        >
          {/* Conversation Stream / Empty State */}
          <div className="flex-1 space-y-4 max-w-3xl mx-auto w-full">
            {!activeConv || activeConv.messages.length === 0 ? (
              <EmptyAskState onSelectSuggestion={handleSendPrompt} />
            ) : (
              <div className="space-y-6">
                {activeConv.messages.map((msg) =>
                  msg.sender === 'user' ? (
                    <UserMessage key={msg.id} text={msg.text} timestamp={msg.timestamp} />
                  ) : (
                    msg.aiData && (
                      <AIResponse
                        key={msg.id}
                        data={msg.aiData}
                        timestamp={msg.timestamp}
                        onSelectFollowUp={handleSendPrompt}
                        onSelectSource={(source) => setSelectedSourceForModal(source)}
                      />
                    )
                  )
                )}

                {/* AI Thinking / Loading State */}
                {isThinking && <AIThinkingState />}
              </div>
            )}
          </div>

          {/* Composer at the bottom */}
          <div className="max-w-3xl mx-auto w-full">
            <AskComposer onSend={handleSendPrompt} isLoading={isThinking} />
          </div>
        </div>

        {/* Right Context Panel (Desktop Sticky Rail) */}
        {isContextPanelOpen && (
          <div className="hidden lg:block lg:col-span-4 xl:col-span-4 sticky top-20">
            <ContextPanel onClose={() => setIsContextPanelOpen(false)} />
          </div>
        )}
      </div>

      {/* Mobile Context Drawer Modal */}
      <Modal
        isOpen={isContextPanelOpen && isMobile}
        onClose={() => setIsContextPanelOpen(false)}
        title="Workspace Context"
        description="Connected context & relationship map"
        maxWidth="sm"
      >
        <ContextPanel onClose={() => setIsContextPanelOpen(false)} />
      </Modal>

      {/* Conversation History Modal */}
      <ConversationHistory
        isOpen={isHistoryOpen}
        onClose={() => setIsHistoryOpen(false)}
        conversations={conversations}
        activeConversationId={activeConversationId || undefined}
        onSelectConversation={(id) => setActiveConversationId(id)}
        onNewConversation={handleNewConversation}
        onRenameConversation={handleRenameConversation}
        onDeleteConversation={handleDeleteConversation}
      />

      {/* Source Detail Modal */}
      <Modal
        isOpen={!!selectedSourceForModal}
        onClose={() => setSelectedSourceForModal(null)}
        title={selectedSourceForModal?.title || 'Source Detail'}
        description={`Connected ${selectedSourceForModal?.connectorName || 'App'} Evidence`}
        maxWidth="md"
        footer={
          <div className="flex items-center justify-between w-full">
            <Button
              variant="outline"
              size="sm"
              onClick={() => {
                if (selectedSourceForModal?.connector) {
                  onOpenConnector?.(selectedSourceForModal.connector as ConnectorId);
                }
              }}
              leftIcon={<ExternalLink className="h-3.5 w-3.5" />}
            >
              Open {selectedSourceForModal?.connectorName}
            </Button>
            <Button variant="primary" size="sm" onClick={() => setSelectedSourceForModal(null)}>
              Done
            </Button>
          </div>
        }
      >
        <div className="space-y-3 text-xs text-slate-700">
          <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200/90 space-y-2">
            <div className="flex items-center justify-between text-slate-900 font-bold">
              <span>{selectedSourceForModal?.title}</span>
              <span className="text-[10px] text-slate-400 font-mono">
                {selectedSourceForModal?.timestamp}
              </span>
            </div>
            <p className="text-slate-600 leading-relaxed text-[11px]">
              {selectedSourceForModal?.snippet}
            </p>
          </div>

          <div className="p-3 rounded-xl bg-indigo-50/60 border border-indigo-100 flex items-center gap-2 text-indigo-900 font-medium text-[11px]">
            <Sparkles className="h-4 w-4 text-indigo-600 fill-indigo-500 shrink-0" />
            <span>
              This context segment was indexed during your latest automatic workspace sync.
            </span>
          </div>
        </div>
      </Modal>
    </div>
  );
};
